### PR TITLE
Add binaryedge update workflow

### PR DESCRIPTION
**Pull request by szepeviktor**
> If anyone is aware of a way to automate this based on their API page I would be interested to see the process.

@SilvrrGIT 

[_source_](https://github.com/szepeviktor/unique-email-address/blob/master/.github/workflows/psl.yml)

### CODE REVIEW

**Comment by szepeviktor** [comment]
⚠️ I may be wrong!

**Comment by SilvrrGIT** [comment]
A quick skim of the code and one issue I see is that the binary_edge list is in json and the list in this repository is just a list.  I am not sure of the capabilities of the diff command but it seems like it would need to be converted first.

**Comment by szepeviktor** [comment]
Lately I've noticed Binaryedge publishing script has a bug 🐞 
There is an empty item on the list: `"159.223.202.119", "", "159.203.0.6"`

**Comment by szepeviktor** [comment]
@SilvrrGIT Feel free to close it.

**Comment by szepeviktor** [comment]
Opens a PR like this _automatically_ https://github.com/szepeviktor/SilvrrGIT_IP-Lists/pull/2

**Pull request closed without merging**
